// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqfwfFxu9a_7z4b7T0lrq-7o2cRjl-HI',
    appId: '1:903686476438:web:f8a3f34e1b5e521486e8b7',
    messagingSenderId: '903686476438',
    projectId: 'finance-tracker-b8fc3',
    authDomain: 'finance-tracker-b8fc3.firebaseapp.com',
    storageBucket: 'finance-tracker-b8fc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe9TI8uNQXEhJlKbpgt0POItzrpqt-KWg',
    appId: '1:903686476438:android:d6aeb4248b97a61086e8b7',
    messagingSenderId: '903686476438',
    projectId: 'finance-tracker-b8fc3',
    storageBucket: 'finance-tracker-b8fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFs8eTgO-t0ljV4Emhhu1i7o09vvKkEk',
    appId: '1:903686476438:ios:329904211ee3945786e8b7',
    messagingSenderId: '903686476438',
    projectId: 'finance-tracker-b8fc3',
    storageBucket: 'finance-tracker-b8fc3.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAFs8eTgO-t0ljV4Emhhu1i7o09vvKkEk',
    appId: '1:903686476438:ios:329904211ee3945786e8b7',
    messagingSenderId: '903686476438',
    projectId: 'finance-tracker-b8fc3',
    storageBucket: 'finance-tracker-b8fc3.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCqfwfFxu9a_7z4b7T0lrq-7o2cRjl-HI',
    appId: '1:903686476438:web:9d69222936bb2ba686e8b7',
    messagingSenderId: '903686476438',
    projectId: 'finance-tracker-b8fc3',
    authDomain: 'finance-tracker-b8fc3.firebaseapp.com',
    storageBucket: 'finance-tracker-b8fc3.firebasestorage.app',
  );
}
